version: "3.8"

services:
  # Ollama service for cloud deployment
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-production
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Pre-pull models on startup
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama3.2:1b &&
        ollama pull llama3.2:latest &&
        wait
      "

volumes:
  ollama_data:
    driver: local 